# Generated by Django 5.2.7 on 2025-11-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='logistics_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='product_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid - Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('refunded', 'Refunded'), ('expired', 'Expired - Auto Refund')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='bank_account',
            field=models.CharField(max_length=50),
        ),
    ]
